spring.application.name=sistema-biblioteca
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema-biblioteca
spring.datasource.username=SEU_USERNAME_AQUI
spring.datasource.password=SUA_SENHA_AQUI
spring.jpa.hibernate.ddl-auto=update