spring.application.name=sistema-biblioteca
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema-biblioteca
spring.datasource.username=postgres
spring.datasource.password=91176621
spring.jpa.hibernate.ddl-auto=update